sonar.projectKey=a24jauhurgon_p0
sonar.organization=a24jauhurgon
sonar.projectName=Quiz Transit - p0
sonar.projectVersion=1.0

# Fitxers a analitzar (JavaScript del frontend)
sonar.sources=.
sonar.inclusions=script.js,admin/admin.js
sonar.exclusions=**/*.php,**/*.css,**/*.html,**/img/**,**/.git/**

# Encoding
sonar.sourceEncoding=UTF-8

# JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
